import type { SkillCategory } from "./types";

export const skillCategories: SkillCategory[] = [
  {
    id: "languages",
    title: "Languages",
    icon: "code",
    skills: ["Python", "TypeScript", "JavaScript (ES6+)", "SQL", "Java"],
  },
  {
    id: "backend",
    title: "Backend",
    icon: "server",
    featured: true,
    skills: [
      "NestJS",
      "FastAPI",
      "Node.js",
      "Express",
      "REST APIs",
      "Microservices",
      "JWT Auth",
      "WebSockets",
      "Async Workers",
      "Rate Limiting",
      "OpenAPI",
      "Multi-Tenancy Patterns",
    ],
  },
  {
    id: "ai-ml",
    title: "AI / ML",
    icon: "ai",
    featured: true,
    skills: [
      "LLM Integration",
      "Groq LLaMA3",
      "OpenAI GPT-4",
      "RAG Pipelines",
      "LangChain",
      "Embeddings",
      "pgvector",
      "Prompt Engineering",
    ],
  },
  {
    id: "frontend",
    title: "Frontend",
    icon: "globe",
    featured: true,
    skills: [
      "React 18",
      "Redux",
      "TypeScript",
      "Vite",
      "TailwindCSS",
      "Bootstrap",
      "Responsive Design",
    ],
  },
  {
    id: "databases",
    title: "Databases",
    icon: "database",
    featured: true,
    skills: [
      "PostgreSQL",
      "Prisma ORM",
      "MongoDB",
      "Redis",
      "pgvector",
      "Query Optimisation",
      "Indexing",
    ],
  },
  {
    id: "devops",
    title: "DevOps & Practice",
    icon: "devops",
    skills: [
      "AWS S3",
      "Docker",
      "CI/CD (GitHub Actions)",
      "Linux",
      "Unit Testing",
      "Code Review",
      "Agile / Scrum",
    ],
  },
  {
    id: "fintech-apis",
    title: "Fintech APIs",
    icon: "fintech",
    skills: [
      "Signzy",
      "DigiLocker",
      "CIBIL",
      "Equifax",
      "CRIF",
      "Razorpay",
      "Easebuzz",
      "Account Aggregator",
      "Penny Drop",
    ],
  },
];
